version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '80:80'
  mysql:
    image: circleci/mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ubuntu
      MYSQL_DATABASE: yiici
      MYSQL_USER: yiici
      MYSQL_PASSWORD: yiici
    volumes: 
      - "mysql-data:/var/lib/mysql:rw"
  redis:
    image: circleci/redis
    ports:
      - "6379:6379"
volumes:
  mysql-data: {}
